mysite/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
	path('cart', include('cart.urls')),
	path('orders', include('orders.urls')),
    path('payment/', include('payment.urls')),
	path('', include('shop.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
	path('',views.order_create, name = 'order_create')
]

mysite/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
	path('', views.product_list, name='product_list'),
	path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
]

mysite/orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from shop.models import Product
from django.conf import settings

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return 'Order {}'.format(self.id)
        
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items',on_delete=models.CASCADE)
	product = models.ForeignKey(Product,
						related_name='order_items',on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)
	
	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

mysite/orders/forms.py
from django import forms
from datetime import date, datetime
from calendar import monthrange
from .models import Order


class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name','last_name', 'email', 'address', 'postal_code', 'city','state',]

mysite/orders/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return redirect(reverse('payment:charge',kwargs={'order_id':order.id}))
    else:
        form = OrderCreateForm()

    return render(request,
            'orders/order/create.html',
            {'cart': cart, 'form': form})

mysite/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
Checkout
{% endblock %}

{% block content %}
    <h1>Checkout</h1>
    
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
            <li>
                {{ item.quantity }}x {{ item.product.name }}
                <span>${{ item.total_price }}</span>
            </li>
            {% endfor %}
        </ul>
    <p>Total: ${{ cart.get_total_price }}</p>
</div>

<form action="{% url 'orders:order_create' %}" method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
</form>
{% endblock %}

mysite/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
	<a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
{% endblock %}