mysite/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
	path('cart', include('cart.urls')),
	path('orders', include('orders.urls')),
    path('payment/', include('payment.urls')),
	path('', include('shop.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/payment/urls.py
from django.urls import path
from . import views

app_name = "payment"
urlpatterns = [
    path('<int:order_id>', views.charge, name="charge")
]

mysite/payment/models.py
from django.db import models

# Create your models here.

mysite/payment/forms.py
from django import forms
from datetime import date, datetime
from calendar import monthrange

class SalePaymentForm(forms.Form):
    MONTH_CHOICES = [(i, i,) for i in range(1, 12)]
    YEAR_CHOICES = [(i, i,) for i in range(2018, 2036)]

    credit_card_number = forms.CharField(label='Credit card number')
    cvv = forms.CharField(label='Security code (CVV)')
    expiry_month = forms.ChoiceField(label="Month", choices=MONTH_CHOICES)
    expiry_year = forms.ChoiceField(label="Year", choices=YEAR_CHOICES)
    stripe_id = forms.CharField(widget=forms.HiddenInput)

mysite/payment/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .forms import SalePaymentForm
from django.template.context_processors import csrf
from cart.cart import Cart
from django.conf import settings
import stripe
from orders.models import Order
from orders.tasks import order_created

# Create your views here.

stripe.api_key = settings.STRIPE_SECRET  

def charge(request,order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == "POST":
        form = SalePaymentForm(request.POST)
 
        if form.is_valid(): # charges the card
            try:
                customer = stripe.Charge.create(
                    amount = int(order.get_total_cost() * 100),
                    currency = "USD",
                    card = form.cleaned_data['stripe_id']
                    )
                order.paid = True
                order.save()
                order_created.delay(order.id)
                return render(request,'orders/order/created.html',{'order': order})
            
            except stripe.CardError as ce:
                messages.error(request, "Your card was declined!")
            
    else:
        form = SalePaymentForm()

    args = {'form': form, 'publishable': settings.STRIPE_PUBLISHABLE, 'order':order}
    args.update(csrf(request))

    return render(request,'payment/payment.html',args)

mysite/payment/templates/payment/payment.html
{% extends "shop/base.html" %}
{% load static from staticfiles %}
{% block head_js %}
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript">
      //<![CDATA[
      Stripe.publishableKey = '{{ publishable }}';
      //]]>
  </script>
  <script type="text/javascript" src="{% static 'payment/js/stripe.js' %}"></script>
{% endblock %}

{% block title %}
Checkout
{% endblock %}

{% block content %}
    <div class="wrapper">
 
  {% for key, value in form.errors.items %}
      <p>{{ value }}</p>
  {% endfor %}
 
  <form role="form" action="{% url 'payment:charge' order.id %}" method="post" id="payment-form">{% csrf_token %}
    {{ form.as_p }}
    <br>
    <input type="submit" value="Charge Me!" />
  </form>
 
</div>
{% endblock %}